#!/bin/sh

wifi () {
	~/.scripts/statusbar/wifi
}

timedate () {
	date +"%I:%M:%S %p"
}


show_day () {
	day=$(date +%-d)
	case "$day" in
		1|21|31) suffix="st" ;;
		2|22)    suffix="nd" ;;
		3|23)    suffix="rd" ;;
		*)       suffix="th" ;;
	esac
	date +"%A, %B $day$suffix %Y"
}

get_ip () {
	fastfetch | grep -m 1 Local | awk '{print $4}' | cut -d '/' -f 1
}

get_keyboard_layout () {  
	layout_id=$(xset -q | grep LED | awk '{ print $10 }')
	case $layout_id in
		"00000000" ) echo "us" ;;
		"00001000" ) echo "intl" ;;
		*) echo "unknown" ;;
	esac
}

get_keyboard_layout_updated () {
    layout_id=$(setxkbmap -query | grep layout | awk ' { print $2 } ')
    case $layout_id in
        "us" ) echo "us" ;;
        "us_intl" ) echo "intl" ;;
        *) echo "unknown" ;;
    esac
}

while :; do
	xsetroot -name "󰣇 $(show_day)"";"" $(get_ip)  $(get_keyboard_layout_updated)  $(wifi)  $(timedate) "
	sleep 1
done
