#!/bin/sh

wifi () {
	~/.scripts/statusbar/wifi
}

timedate () {
	date +"%I:%M:%S %p"
}


show_day () {
	day=$(date +%-d)
	case "$day" in
		1|21|31) suffix="st" ;;
		2|22)    suffix="nd" ;;
		3|23)    suffix="rd" ;;
		*)       suffix="th" ;;
	esac
	date +"%A, %B $day$suffix %Y"
}

get_ip () {
	ip addr show | grep 192 | awk '{print $2}' | cut -d/ -f1
}

while :; do
	xsetroot -name "󰣇 $(show_day)"";""$(get_ip)  $(wifi)  $(timedate) "
	sleep 1
done
